#### 1. Import the numpy package under the name `np` (★☆☆)
导入numpy库并简写为np

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
打印numpy的版本和配置说明

In [3]:
print(np.__version__)
print(np.show_config())

1.15.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/frankfwu/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/frankfwu/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/frankfwu/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/frankfwu/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/frankfwu/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/frankfwu/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/frankfwu/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/frankfwu/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Use

#### 3. Create a null vector of size 10 (★☆☆)
创建一个长度为10的空向量

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)
如何找到任何一个数组的内存大小？

In [10]:
Z = np.zeros((10,10))
print(Z.size)
print(Z.itemsize)
print(Z.size*Z.itemsize)

100
8
800


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)
如何从命令行得到numpy中add函数的说明文档？

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
创建一个长度为10并且除了第五个值为1的空向量。

In [13]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
创建一个值域范围从10到49的向量。

In [14]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)
反转一个向量（第一个元素变为最后一个元素）

In [16]:
z = np.arange(0,10)
print(z)
z = z[::-1]
print(z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
创建一个3X3并且值从0到8的矩阵。

In [17]:
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
找到数组\[1,2,0,0,4,0\]中非0元素的位置索引

In [19]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)
创建一个3x3的单位矩阵

In [24]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)
创建一个3x3x3的随机数组

In [27]:
arr = np.random.randn(27).reshape(3,3,3)
arr

array([[[ 0.99859152, -0.54137441,  1.85490379],
        [-0.49956734, -1.56555671, -1.68997736],
        [ 0.17388795, -0.32687775, -0.82107626]],

       [[ 0.41426907,  0.55900307,  0.09855523],
        [ 0.5279949 ,  0.18889893, -1.5251927 ],
        [-0.08032122,  1.11444875, -0.57455475]],

       [[-1.11941032,  1.79707343, -0.39276639],
        [-1.68160161,  0.06832483, -0.29624148],
        [ 0.0999518 , -0.76971147,  0.36391274]]])

In [28]:
arr = np.random.random((3,3,3))
arr

array([[[0.51920842, 0.9849693 , 0.86398095],
        [0.07099011, 0.53411049, 0.94262731],
        [0.59192369, 0.30812702, 0.88601492]],

       [[0.05525236, 0.61659865, 0.75950925],
        [0.52981841, 0.67205621, 0.39870787],
        [0.26378816, 0.5272909 , 0.45705933]],

       [[0.89466129, 0.40160279, 0.78380668],
        [0.13497739, 0.11601361, 0.27321388],
        [0.36024454, 0.58950838, 0.52311878]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
创建一个10x10的随机数组并找到它的最大值和最小值

In [29]:
arr = np.random.random((10,10))
print(arr.max())
print(arr.min())

0.9952002152110193
0.0014248351370527157


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
创建一个长度为30的随机向量并找到它的平均值

In [30]:
arr = np.random.random(30)
print(arr.mean())

0.4821524819620656


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
创建一个二维数组，其中边界值为1，其余值为0

In [36]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
arr = np.zeros((8,8))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
对于一个存在的数组，如何添加一个用0填充的边界？

In [35]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
以下表达式运行的结果分别是什么

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [41]:
0 * np.nan

nan

In [43]:
np.nan == np.nan

False

In [44]:
np.inf > np.nan

False

In [46]:
np.nan - np.nan

nan

In [47]:
np.nan in set([np.nan])

True

In [52]:
0.3 == 3*0.1

False

In [51]:
0.3 is 3*0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
创建一个5x5的矩阵，并设置值1，2，3，4落在其对角线下方位置

In [57]:
#arr = np.diag(1+np.arange(5), k=0)
#arr

In [53]:
arr = np.diag(1+np.arange(4), k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
创建一个8x8的矩阵，并设置成棋盘样式

In [60]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
考虑一个（6，7，8）形状的数组，其第100个元素的索引（x，y，z）是什么？

In [61]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
用tile函数去创建一个8x8的棋盘样式矩阵

In [63]:
arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)
对一个5x5的随机矩阵做归一化

In [66]:
arr = np.random.randn(5,5)
arr_max, arr_min = arr.max(), arr.min()
arr = (arr - arr_min)/(arr_max - arr_min)
arr

array([[0.17851172, 0.50006219, 0.88014126, 0.38331441, 0.72819781],
       [0.51298854, 0.95720204, 0.79726194, 0.63299792, 1.        ],
       [0.72314513, 0.99011027, 0.75887117, 0.54046592, 0.78762411],
       [0.80001982, 0.        , 0.49018041, 0.76601651, 0.42990499],
       [0.17791341, 0.65162226, 0.19449149, 0.47414787, 0.88478924]])

In [67]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
Z

array([[0.44213469, 0.83947636, 0.1260044 , 0.57681676, 0.27266847],
       [0.83490093, 0.13706619, 0.32050509, 0.75405421, 0.42551175],
       [0.07681208, 0.23644696, 0.07779583, 0.82493009, 0.12780826],
       [1.        , 0.        , 0.74410352, 0.98727807, 0.38541539],
       [0.15955084, 0.04154621, 0.64386238, 0.69495918, 0.9378953 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype？

In [75]:
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么

In [77]:
x = np.ones((5,3))
y = np.ones((3,2))
print(x.dot(y))
print(np.dot(x,y))
print(x @ y)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
给定一个一维数组，对其在3到8之间的所有元素取反

In [78]:
z = np.arange(11)
z[(3 < z) & (z <= 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
下面脚本运行后的结果是什么

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [83]:
print(sum(range(5),-1))# 返回结果9

10


In [80]:
from numpy import *
print(sum(range(5),-1))#返回结果10

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
考虑一个整数向量Z，下列表达合法的是哪个？

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [85]:
z = np.arange(10)
print(z**z)
print(2 <<z>> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
print(z<z>z)#不合法

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [95]:
z = np.arange(10)
print(z)
print(2 <<z>> 2)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   4   8  16  32  64 128 256]


#### 28. What are the result of the following expressions?
下列表达式的结果分别是什么？

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [90]:
np.array(0) / np.array(0)

/Users/frankfwu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [91]:
np.array(0) // np.array(0)

/Users/frankfwu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [92]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)
如何从零位对浮点数组做舍入？

In [96]:
Z = np.random.uniform(10,10,10)
np.copysign(np.ceil(np.abs(Z)), Z)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

#### 30. How to find common values between two arrays? (★☆☆)
如何找到两个数组中的共同元素？

In [111]:
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
np.intersect1d(z1, z2)#intersect1d中是数字1，不是字母l

array([4, 5, 6, 7, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
如何忽略所有的numpy警告（尽量不建议这么做）？

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
#An equivalent way, with a context manager:
with np.errstate(divide="ignore"):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
下面的表达式是正确的吗？

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [112]:
np.sqrt(-1) == np.emath.sqrt(-1)#False

/Users/frankfwu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
如何得到昨天、今天、明天的日期？

In [114]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-06-22
2019-06-23
2019-06-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
如何得到所有与2016年7月对应的日期？

In [115]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)
如何直接在位计算（A+B)\*(-A/2)(不建立副本）？

In [118]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A, B, out=B)

array([3., 3., 3.])

In [119]:
np.divide(A, 2, out=A)

array([0.5, 0.5, 0.5])

In [120]:
np.negative(A, out=A)

array([-0.5, -0.5, -0.5])

In [121]:
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)
用五种不同的方法去提取一个随机数组的整数部分

In [123]:
z = np.random.uniform(0,10,10)
print(z - z%1)

[4. 5. 5. 4. 4. 1. 8. 1. 5. 7.]


In [125]:
np.floor(z)

array([4., 5., 5., 4., 4., 1., 8., 1., 5., 7.])

In [126]:
np.ceil(z)-1

array([4., 5., 5., 4., 4., 1., 8., 1., 5., 7.])

In [127]:
z.astype(int)

array([4, 5, 5, 4, 4, 1, 8, 1, 5, 7])

In [128]:
np.trunc(z)

array([4., 5., 5., 4., 4., 1., 8., 1., 5., 7.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
创建一个5x5的矩阵，其中每行的数值范围从0到4

In [129]:
z = np.zeros((5,5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
通过考虑一个可生成10个整数的函数，来构建一个数值

In [130]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(), dtype=float, count=-1)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
创建一个长度为10的随机向量，其取值范围从0到1，但是不包括0和1

#### 40. Create a random vector of size 10 and sort it (★★☆)
创建一个长度为10的随机向量，并将其排序

#### 41. How to sum a small array faster than np.sum? (★★☆)
对于一个小数组，如何用比np.sum更快的方式对其求和？

#### 42. Consider two random array A and B, check if they are equal (★★☆)
对于两个随机数组A和B，检查他们是否相等

#### 43. Make an array immutable (read-only) (★★☆)
创建一个只读数组（read-only)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
创建一个长度为10的向量，并将向量中最大值替换为1

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)
创建一个结构化数组，并实现x和y坐标覆盖\[0,1\]x\[0,1\]区域

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
打印没个numpy标量类型的最小值和最大值

#### 49. How to print all the values of an array? (★★☆)
如何打印一个数组中的所有数值？

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
给定标量时，如何找到数组中最接近标量的值

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
创建一个表示位置（x,y)和颜色(r,g,b)的结构化数组

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
对一个表示坐标形状为（100，2）的随机向量，找到点与点的距离

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
如何将32位的浮点数（float）转换为对应的整数（integer）

#### 54. How to read the following file? (★★☆)
如何读取以下文件？

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
对于numpy数组，enumerate的等价操作是什么？

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
生成一个通用的二维Gaussian-like数组

#### 57. How to randomly place p elements in a 2D array? (★★☆)
对一个二维数组，如何在其内部随机放置p个元素？

#### 58. Subtract the mean of each row of a matrix (★★☆)
减去一个矩阵中的每一行的平均值

#### 59. How to sort an array by the nth column? (★★☆)
如何通过第n列对一个数组进行排序？

#### 60. How to tell if a given 2D array has null columns? (★★☆)
如何检查一个二维数组是否有空列？

#### 61. Find the nearest value from a given value in an array (★★☆)
从数组中的给定值中找出最近的值

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
如何用迭代器（iterator）计算两个分别具有形状（1，3）和（3，1）的数组？

#### 63. Create an array class that has a name attribute (★★☆)
创建一个具有name属性的数组类

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
考虑一个给定的向量，如何对由第二个向量索引的每个元素加1（小心重复的索引）？

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
根据索引列表（I），如何将向量（X）的元素累加到数组（F)？

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
考虑一个(dtype=ubyte)的(w,h,3)图像，计算其唯一颜色的数量

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
考虑一个四维数组，如何一次性计算出最后两个轴（axis）的和？

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

#### 69. How to get the diagonal of a dot product? (★★★)
如何获得点积dot product的对角线？

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
考虑一个向量\[1, 2, 3, 4, 5\]，如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
考虑一个维度（5，5，3）的数组，如何将其与一个（5，5）的数组相乘？

#### 72. How to swap two rows of an array? (★★★)
如何对一个数组中任意两行做交换？

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C

#### 75. How to compute averages using a sliding window over an array? (★★★)
如何通过滑动窗口计算一个数组的平均值？

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)
考虑一维数组Z,构建一个二维数组的第一行(Z\[0\],Z\[1\],Z\[2\]) 和随后的每一行转移1(最后一行应该(Z\[-3\],Z\[-2\],Z\[-1\])）

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
如何对布尔值取反，或者原位（in-place）改变浮点数的符号（sign）？

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)
考虑两组点集P0和P1去描述一组线（二维）和一个点p，如何计算点p到每一条线 i(P0\[i\],P1\[i\])的距离？

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)
考虑两组点集P0和P1去描述一组线（二维）和一个点p，如何计算每一个点j(P\[j\])到每一条线 i(P0\[i\],P1\[i\])的距离？

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
考虑一个任意数组，编写一个函数，该函数提取形状固定的子部分，并以给定元素为中心(在必要时填充值)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)
考虑一个数组Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\],如何生成一个数组R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]？

#### 82. Compute a matrix rank (★★★)
计算一个矩阵的秩

#### 83. How to find the most frequent value in an array?
如何找到一个数组中出现频率最高的值？

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
从一个10x10的矩阵中提取出连续的3x3区块

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)
创建一个满足Z\[i,j\] == Z\[j,i\]的子类

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
考虑p个nxn矩阵和一组形状为（n，1）的向量，如何直接计算p个矩阵的乘积（n，1）？

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
对于一个16x16的数组，如何找到一个区域（block-sum）的和 (区域大小为4x4)？

#### 88. How to implement the Game of Life using numpy arrays? (★★★)
如何利用numpy数组实现Game of Life？

#### 89. How to get the n largest values of an array (★★★)
如何找到一个数组的第n个最大值？

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
给定任意个数向量，创建笛卡尔积（每一个元素的每一种组合）

#### 91. How to create a record array from a regular array? (★★★)
如何从一个正常数组创建记录数组（record array）？

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
考虑一个大向量Z，用三种不同的方法计算它的立方

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
考虑两个形状分别为（8，3）和（2，2）的数组A和数组B，如何在数组A中找到满足包含B中元素的行?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)
考虑一个10x3的矩阵，分解出有不全相同值的行(如 \[2,2,3\])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
将一个整数向量转换为matrix binary 的表现形式

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
给定一个二维数组，如何提取出唯一的（unique）行？

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
考虑两个向量A和B，写出用einsum等式对应的inner，outer，sum，mul函数

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
考虑一个由两个向量描述的路径(X,Y)，如何用等距样例（equidistant samples）对其进行采样（sample）？

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
给定一个整数n和一个二维数组X，从X中选择可以表示为n次多项式分布的行，即，只包含整数和为n的行。

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值