In [46]:
import numpy as np

#### 1、随机生成数组（random）

In [4]:
data = np.random.randn(2,3)
print(data)

[[ 1.37963315 -1.28459729 -0.35481078]
 [-1.29138077 -0.6721072   0.87789664]]


In [5]:
data*10

array([[ 13.79633153, -12.84597285,  -3.54810784],
       [-12.91380765,  -6.72107197,   8.77896644]])

In [6]:
data+data

array([[ 2.75926631, -2.56919457, -0.70962157],
       [-2.58276153, -1.34421439,  1.75579329]])

In [44]:
data.shape

(2, 3)

In [45]:
data.dtype

dtype('float64')

#### 2、列表的转换

In [12]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int64')

#### 3、zeros、ones、empty、arange创建数组

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.empty(5)

array([6. , 7.5, 8. , 0. , 1. ])

In [26]:
np.empty((2,3))

array([[2.75926631, 2.56919457, 0.70962157],
       [2.58276153, 1.34421439, 1.75579329]])

In [43]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### 4、ndarray的数据类型

In [47]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int64)
arr1.dtype

dtype('float64')

In [48]:
arr2.dtype

dtype('int64')

In [49]:
print(arr1)
print(arr2)

[1. 2. 3.]
[1 2 3]


In [50]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [51]:
float_arr = arr.astype(np.float64)#使用astype方法显示地转换数组的数据类型
float_arr.dtype

dtype('float64')

In [55]:
arr_float = np.array([1.22, 2.12, 3.15, 4.11, 5.00])
arr1_float = np.array([1.82, 2.92, 3.95, 4.91, 5.90])
print(arr_float)
print(arr1_float)

[1.22 2.12 3.15 4.11 5.  ]
[1.82 2.92 3.95 4.91 5.9 ]


In [56]:
arr_int = arr_float.astype(np.int64)#当浮点数类型转化为整数类型时，只保留整数位
arr1_int = arr1_float.astype(np.int64)
print(arr_int)
print(arr1_int)

[1 2 3 4 5]
[1 2 3 4 5]


In [62]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)#通过astype将表达数字的字符串转换为数字格式
print(numeric_strings)
print(numeric_strings.astype(float))

[b'1.25' b'-9.6' b'42']
[ 1.25 -9.6  42.  ]


#### 5、numpy的数组算术

In [63]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [64]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [65]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [67]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [69]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [70]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### 6、基础索引与切片

In [71]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr[5]

5

In [73]:
arr[5:8]

array([5, 6, 7])

In [81]:
arr[5:8] = 12#如果传入一个数值给数组的切片，数值被传递给整个切片，区别于Python的内建列表，数组的切片是原数组的视图，
#这意味着数据并不是被复制了，任何对于视图的修改都会反映到原数组上。
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [77]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [78]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [80]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [82]:
arr[5:8].copy()#如果想要一份数组切片的拷贝而不是视图的话，就必须显示的复制这个数组

array([12, 12, 12])

In [84]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
'''对于高维度的数组，其索引值对应的是数组而不是一个值'''
arr2d[2]

array([7, 8, 9])

In [85]:
arr2d[2][1]

8

In [86]:
arr2d[2, 1]

8

In [87]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr3d[0,0,0]

1

In [90]:
arr3d[0,1,0]

4

In [91]:
arr3d[0, :1, :1]

array([[1]])

In [94]:
arr3d[0, 1, :]

array([4, 5, 6])

In [95]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [96]:
data

array([[ 2.1564368 , -2.01061502,  0.20164463, -0.04740493],
       [ 0.9478813 , -0.6476822 , -1.87418729,  1.56635252],
       [ 0.28183243, -0.0875206 ,  0.42795383, -0.84145571],
       [ 1.26084914,  1.43223106, -0.36836813,  1.43502485],
       [ 2.12286406, -0.71590785, -1.10302206,  0.08810825],
       [ 0.77051744,  0.18644402, -0.72787116,  0.85719465],
       [-0.54065985,  0.29598401, -1.08566423, -0.77213336]])

In [97]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [98]:
data[names=='Bob']

array([[ 2.1564368 , -2.01061502,  0.20164463, -0.04740493],
       [ 1.26084914,  1.43223106, -0.36836813,  1.43502485]])

In [99]:
data[names=='Bob', 2:]

array([[ 0.20164463, -0.04740493],
       [-0.36836813,  1.43502485]])

In [100]:
data[names=='Bob', 3]

array([-0.04740493,  1.43502485])

In [101]:
data[~(names=='Bob')]

array([[ 0.9478813 , -0.6476822 , -1.87418729,  1.56635252],
       [ 0.28183243, -0.0875206 ,  0.42795383, -0.84145571],
       [ 2.12286406, -0.71590785, -1.10302206,  0.08810825],
       [ 0.77051744,  0.18644402, -0.72787116,  0.85719465],
       [-0.54065985,  0.29598401, -1.08566423, -0.77213336]])

In [102]:
data[names!='Bob']

array([[ 0.9478813 , -0.6476822 , -1.87418729,  1.56635252],
       [ 0.28183243, -0.0875206 ,  0.42795383, -0.84145571],
       [ 2.12286406, -0.71590785, -1.10302206,  0.08810825],
       [ 0.77051744,  0.18644402, -0.72787116,  0.85719465],
       [-0.54065985,  0.29598401, -1.08566423, -0.77213336]])

In [103]:
data[~(names=='Bob')] == data[names!='Bob']

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [104]:
data[~(names=='Bob')] is data[names!='Bob']

False

In [105]:
data[~(names=='Bob')] is not data[names!='Bob']

True

In [106]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [107]:
data[mask]

array([[ 2.1564368 , -2.01061502,  0.20164463, -0.04740493],
       [ 0.28183243, -0.0875206 ,  0.42795383, -0.84145571],
       [ 1.26084914,  1.43223106, -0.36836813,  1.43502485],
       [ 2.12286406, -0.71590785, -1.10302206,  0.08810825]])

In [108]:
arr = np.empty((8, 4))

In [109]:
for i in range(8):
    arr[i] = i

In [110]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [111]:
arr[[4, 3, 1, 0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [112]:
arr[[-3, -7, 0]]

array([[5., 5., 5., 5.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [113]:
arr[[-7]] == arr[[1]]

array([[ True,  True,  True,  True]])

In [115]:
arr[[-7]] is arr[[1]]

False

In [117]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [119]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [124]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [126]:
arr[[1,5,7,2]][:, [0,3,1,2]]#神奇索引与切片不同，它总是将数据复制到一个新的数组中

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [132]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [133]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [135]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [136]:
np.dot(arr, arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [130]:
arr = np.random.randn(6, 3)
arr

array([[-0.98661115,  0.84322212,  1.32594121],
       [-0.25739601,  0.70477132, -2.4347988 ],
       [ 0.44904437,  0.29567559, -0.7847149 ],
       [-0.34642379,  0.86934445,  0.44789859],
       [ 2.31061316,  0.66364695,  0.62748272],
       [-0.40282837, -1.10388376, -0.66783171]])

In [131]:
np.dot(arr.T, arr)

array([[6.86250843, 0.79637926, 0.52987596],
       [0.79637926, 3.70989662, 0.71307927],
       [0.52987596, 0.71307927, 9.34248971]])

In [138]:
arr3d = np.arange(16).reshape((2, 2, 4))
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [141]:
arr3d.transpose((1, 0, 2))#x轴与y轴对换

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [142]:
arr3d.transpose((0, 1, 2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [143]:
arr3d.transpose((0, 2, 1))#y轴与z轴对换

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [144]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [145]:
arr3d.swapaxes(1,2)#该方法接收一对轴编号作为参数，并对轴进行调整用于重组数据，swapaxes返回视图，并没有对数据进行复制

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [147]:
arr3d.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [148]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [150]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [152]:
x = np.random.randn(8)
y = np.random.randn(8)#逐个元素的将x和y中的最大值返回
x

array([ 0.57050963, -1.83916062,  0.86048233,  0.08949363, -1.56373608,
       -0.33250511, -0.72071341, -0.13728909])

In [153]:
y

array([-0.83099508,  0.18133756,  0.13434927, -0.2142916 ,  0.57294316,
       -0.12086834, -0.50657274, -0.9031853 ])

In [154]:
np.maximum(x,y)

array([ 0.57050963,  0.18133756,  0.86048233,  0.08949363,  0.57294316,
       -0.12086834, -0.50657274, -0.13728909])

In [155]:
arr = np.random.randn(7)*5
arr

array([ 2.07944098, -6.37114503,  0.07105854,  9.41656276, -6.27685116,
        3.43953455, -0.48078138])

In [157]:
remainder, whole_part = np.modf(arr)#返回整数部分与小数部分
remainder

array([ 0.07944098, -0.37114503,  0.07105854,  0.41656276, -0.27685116,
        0.43953455, -0.48078138])

In [158]:
whole_part

array([ 2., -6.,  0.,  9., -6.,  3., -0.])

#### 7、使用数组进行面向数组编程

In [159]:
points = np.arange(-5,5,0.01)#1000个等距点
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [160]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [165]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image polt of $\sqrt{x^2 +y^2)}$ for a grid of values")

Text(0.5, 1.0, 'Image polt of $\\sqrt{x^2 +y^2)}$ for a grid of values')

In [167]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
         for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [168]:
result_where = np.where(cond, xarr, yarr)
result_where

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [170]:
arr = np.random.randn(4, 4)
np.where(arr > 0, 1, 0)

array([[0, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 1, 0]])

In [171]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [172]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [173]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [174]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [175]:
arr.cumprod(axis=0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

In [177]:
arr = np.random.randn(100)
(arr > 0).sum()#正值的个数

48

In [178]:
(arr > 0).any()#any检查数组中至少有一个True

True

In [179]:
(arr > 0).all()#all检查数组中是否每个都是True

False

In [180]:
arr = np.random.randn(6)
arr

array([-1.35047001,  0.17513397, -0.60539446,  1.07274932,  0.83151728,
        0.12766087])

In [181]:
arr.sort()#按照升序排列
arr

array([-1.35047001, -0.60539446,  0.12766087,  0.17513397,  0.83151728,
        1.07274932])

In [202]:
arr = np.random.randn(5,3)
arr

array([[-1.89208506, -0.00967142, -0.3729622 ],
       [ 0.06538159,  0.68985294,  0.78991453],
       [-0.67600553,  0.22517332,  0.03984772],
       [ 0.0466816 , -0.14588618, -0.19413506],
       [ 0.91297186,  0.89687975,  0.89313729]])

In [203]:
#print(arr.sort(1))
np.sort(arr)

array([[-1.89208506, -0.3729622 , -0.00967142],
       [ 0.06538159,  0.68985294,  0.78991453],
       [-0.67600553,  0.03984772,  0.22517332],
       [-0.19413506, -0.14588618,  0.0466816 ],
       [ 0.89313729,  0.89687975,  0.91297186]])

In [204]:
arr

array([[-1.89208506, -0.00967142, -0.3729622 ],
       [ 0.06538159,  0.68985294,  0.78991453],
       [-0.67600553,  0.22517332,  0.03984772],
       [ 0.0466816 , -0.14588618, -0.19413506],
       [ 0.91297186,  0.89687975,  0.89313729]])

In [195]:
print(arr)
arr.sort(0)
arr

[[-0.99232887 -0.1225066   1.06160892]
 [-1.35301298 -0.43184959  0.35997124]
 [-0.72866847 -0.29926356 -0.24731072]
 [-1.63764968 -0.71668153  0.54548718]
 [-0.67580812 -0.19194083  0.0235078 ]]


array([[-1.63764968, -0.71668153, -0.24731072],
       [-1.35301298, -0.43184959,  0.0235078 ],
       [-0.99232887, -0.29926356,  0.35997124],
       [-0.72866847, -0.19194083,  0.54548718],
       [-0.67580812, -0.1225066 ,  1.06160892]])

In [205]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [206]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [207]:
ints = np.array([3, 3, 3, 2, 2, 2, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [208]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [210]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])#in1d中是数字1，不是字母l

array([ True, False, False,  True,  True, False,  True])

#### 8、使用数组进行文件输入和输出

In [211]:
arr = np.arange(10)
np.save('some_array', arr)#存储数据，后缀为.npy

In [212]:
np.load('some_array.npy')#读取数据

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 9、线性代数

In [213]:
x = np.arange(8).reshape(2,4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [215]:
y = np.arange(8).reshape(4,2)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [216]:
x.dot(y)

array([[28, 34],
       [76, 98]])

In [217]:
np.dot(x,y)

array([[28, 34],
       [76, 98]])

In [218]:
np.dot(x, np.ones(4))#一个二维数组和一个长度合适的一维数组的矩阵乘积，其结果是一个一维数组

array([ 6., 22.])

In [220]:
x @ np.ones(4)#@也作为中辍操作符，用于点乘矩阵的操作

array([ 6., 22.])

In [221]:
x @ y

array([[28, 34],
       [76, 98]])

In [222]:
from numpy.linalg import inv, qr

In [223]:
X = np.random.randn(5,5)
mat = X.T.dot(X)
inv(mat)

array([[  0.5193875 ,  -0.65618313,   0.36484558,   0.78014346,
         -1.05019161],
       [ -0.65618313,  55.7522628 , -21.83322972, -29.53821631,
         21.16877394],
       [  0.36484558, -21.83322972,   8.88653486,  11.80278797,
         -8.24248173],
       [  0.78014346, -29.53821631,  11.80278797,  16.28815188,
        -11.86094104],
       [ -1.05019161,  21.16877394,  -8.24248173, -11.86094104,
         10.17409823]])

In [224]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  2.04618083e-16, -1.22439629e-15,
         5.69827064e-15, -2.91914477e-15],
       [-1.99295333e-16,  1.00000000e+00, -1.90589657e-15,
        -1.32069771e-14,  4.76014005e-16],
       [-6.86126121e-17, -4.35334428e-15,  1.00000000e+00,
         1.58545585e-15, -5.11445439e-15],
       [ 2.45454480e-16,  1.45927403e-14, -1.67635435e-15,
         1.00000000e+00,  1.14956028e-15],
       [-1.47354561e-16, -5.39634997e-15,  1.89409556e-16,
        -7.98483003e-17,  1.00000000e+00]])

In [225]:
q, r = qr(mat)
r

array([[-9.01099778,  3.33174259,  0.7977511 ,  4.26667057, -2.26445448],
       [ 0.        , -1.07453508, -3.41999735,  0.78989974,  0.38281391],
       [ 0.        ,  0.        , -4.96980957,  4.85490946,  1.65548304],
       [ 0.        ,  0.        ,  0.        , -0.43616378, -0.59422484],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.03624158]])

In [232]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
    
plt.plot(walk[:100])
    

In [233]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
walk.min()

-9

In [235]:
walk.max()

23

In [236]:
(np.abs(walk) >= 10).argmax()

51

In [237]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) #0 或 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

array([[ -1,  -2,  -3, ..., -38, -39, -40],
       [  1,   2,   3, ..., -12, -13, -12],
       [  1,   0,  -1, ...,  40,  39,  38],
       ...,
       [  1,   0,   1, ...,  64,  65,  64],
       [  1,   2,   3, ..., -36, -35, -36],
       [ -1,  -2,  -1, ...,  14,  13,  12]])

In [238]:
walks.max()

125

In [239]:
walks.min()

-131

In [240]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

array([ True, False,  True, ...,  True,  True, False])

In [242]:
hits30.sum()

3371

In [243]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

500.6535152773658

In [244]:
steps = np.random.normal(loc=0, scale=0.25, size=(nwalks, nsteps))
steps

array([[ 0.32301101, -0.16797635,  0.04805838, ..., -0.15213415,
        -0.29258314,  0.23237701],
       [-0.11359803,  0.26944736,  0.11252505, ...,  0.05033515,
        -0.19280467, -0.18597035],
       [ 0.19048628, -0.28688267,  0.22288934, ...,  0.03103915,
         0.03836535,  0.14608935],
       ...,
       [ 0.0336665 , -0.01262313, -0.12906425, ..., -0.20375285,
        -0.55713793,  0.10548012],
       [-0.28673675,  0.06740927, -0.04628521, ..., -0.48468528,
        -0.01802769, -0.17393239],
       [ 0.14155971, -0.4144757 ,  0.30224691, ..., -0.15189199,
         0.04520363,  0.26547022]])